### ISSUE TITLE
Error with some Bladebit C7 plots

### ISSUE THREAD

**Issue by Jsewill** [foxypool/foxy-farmer#10]
foxy-farmer chokes on about 144 of my Bladebit C7 plots. A lot of these sorts of errors:

```shell
ERROR    Failed to open file <redacted plot path> badbit or failbit after reading size 4 at position 0 Traceback (most recent call last):
  File "<redacted path>/foxy-farmer/venv/lib/python3.11/site-packages/chia/plotting/manager.py", line 326, in process_file
    prover = DiskProver(str(file_path))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: badbit or failbit after reading size 4 at position 0
```

These same plots have been farmed just fine in chia since I plotted them.

**Comment by felixbrucker** [comment]
Can you check if there are any differences regarding harvester settings in `.foxy-farmer/mainnet/config/config.yaml` and your chia config.yaml in `.chia/mainnet/config/config.yaml`?

Running the chia harvester on the same system using the same chia version (2.1.0) works fine, no such errors in the chia debug.log?

**Comment by Jsewill** [comment]
The harvester settings are exactly the same. I also see the foxy config has different payout instructions.

**Comment by felixbrucker** [comment]
Did you run chia 2.1.0 on the same system for comparison?

**Comment by Jsewill** [comment]
I have run chia 2.1 successfully, without error, before and after trying this.

**Comment by felixbrucker** [comment]
Just to confirm, you are using the GPU, not CPU? if using the CPU can you try using the GPU?

**Comment by Jsewill** [comment]
I'm using the GPU.

**Comment by felixbrucker** [comment]
Weird indeed, i got users farming 1pib of compressed bladebit plots just fine
It's not some weird permission issue or some other program interfering?

Which OS are you using and did you try on another machine?

**Comment by Jsewill** [comment]
Like I mentioned at first, only some of my plots don't work with it. It didn't complain about most of them. I haven't dug into your code very far, but perhaps you're using an old version of chiapos?

No, I have not tried another machine. No, my permissions are exactly the same for all the plots.

This farmer is running Ubuntu server, and is up-to-date. As I said earlier, regular chia works just fine with these plots.

**Comment by felixbrucker** [comment]
> I haven't dug into your code very far, but perhaps you're using an old version of chiapos?

i just use what ships with chia 2.1.0

**Comment by Jsewill** [comment]
This seems to have been a problem with btrfs. After a reboot, it stopped complaining.

**Comment by felixbrucker** [comment]
Very weird that the application layer was impacted like that (one working, the other having some issues).
Now thinking about it it could have been related to the plot cache, which would be present and populated for your existing install but empty for the new foxy-farmer one, so it would need to read more data from the plots once to populate the cache.

Anyway, glad you got it resolved 👍
