### ISSUE TITLE
ModuleNotFoundError: No module named 'foxy_farmer.cmds'

### ISSUE THREAD

**Issue by MrMinemeet** [foxypool/foxy-farmer#5]
Hello there,

it seems that something is a bit messed up with the 1.6.0 release.

When installing it from source and then running `foxy-farmer` it results in a "_ModuleNotFoundError: No module named 'foxy_farmer.cmds_'".

More precisely, the full error is this one:

```
Traceback (most recent call last):
  File "/home/user/.local/bin/foxy-farmer", line 5, in <module>
    from foxy_farmer.foxy_farmer_main import main
  File "/home/user/.local/lib/python3.10/site-packages/foxy_farmer/foxy_farmer_main.py", line 32, in <module>
    from foxy_farmer.cmds.farm_summary import summary_cmd
ModuleNotFoundError: No module named 'foxy_farmer.cmds'
```

I tried it on different devices(pi4 with raspberry OS 64-bit, PC with pop! and fedora) and it is always the same error. 
When checking out version 1.5.1 and trying it, it works without issues.

The odd thing is, when opening the repo in PyCharm and running the `foxy_farmer_main.py`, it will work with 1.6.0.

**Comment by felixbrucker** [comment]
Thanks for reporting, I'll take a look and try to repro :+1:

**Comment by felixbrucker** [comment]
Pushed a fix, can you try if the issue still exists with the current `main` branch?

**Comment by MrMinemeet** [comment]
Works without issues now.
Thanks for the quick fix!
